variables:
  type: 'Docs'
  versionSpec: '10.x'
  ghRef: 'github.com/PyroTechniac/spooky'
  targetBranch: 'master'


trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(versionSpec)
    displayName: 'Install Node'
  - script: yarn
    displayName: 'Install Dependencies'
  - bash: |
      git clone $(git config remote.origin.url) out -b $TARGET_BRANCH
      yarn docs:build
      mv docs/docs.json out/docs/docs.json
      mv docs/docs.md out/docs/docs.md
      cd out
      git add --all .
      git config user.name "Azure Pipelines"
      git config user.email "${COMMIT_EMAIL}"
      git commit -m "$TYPE build: $(git rev-parse --verify HEAD)"
      git push "https://${GH_TOKEN}@${GH_REF}" $TARGET_BRANCH
    env:
      GH_TOKEN: $(ghToken)
      COMMIT_EMAIL: $(commitEmail)
      TYPE: $(type)
      GH_REF: $(ghRef)
      BRANCH: $(Build.SourceBranchName)
      TARGET_BRANCH: $(targetBranch)
    displayName: Build $(type)